### ISSUE TITLE
Traceback (most recent call last):   File "demo.py", line 11, in <module>     from model import Model   File "/home/anbanglee/SC-FEGAN-master/model.py", line 4, in <module>     from ops import *   File "/home/anbanglee/SC-FEGAN-master/ops.py", line 9     """       ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jackylee1** [JoYoungjoo/SC-FEGAN#18]
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from model import Model
  File "/home/anbanglee/SC-FEGAN-master/model.py", line 4, in <module>
    from ops import *
  File "/home/anbanglee/SC-FEGAN-master/ops.py", line 9
    """
      ^
SyntaxError: invalid syntax
？
what's wrong ?i use python3

**Comment by advandced** [comment]
I have the same issue

**Comment by mostafasadeghi97** [comment]
just delete the three comment lines
like this : 

@add_arg_scope
def gate_conv(x_in, cnum, ksize, stride=1, rate=1, name='conv',
             padding='SAME', activation='leaky_relu', use_lrn=True,training=True):
    assert padding in ['SYMMETRIC', 'SAME', 'REFELECT']
